server:
  port: 11002
  servlet:
    context-path: /qjwdzs
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://124.70.156.133:5432/qjwdzs
    #    username: postgres
    #    password: ovit@123!
    url: jdbc:postgresql://localhost:5432/qjwdzs
    username: postgres
    password: 123456
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 50000
#    password: ovit

  # 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always

mybatis-plus:
  mapper-locations: classpath*:/**/mapper/**/*Mapper.xml
  global-config:
    # 热加载，生产环境建议关闭
    refresh: false
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    db-config:
      #逻辑未删除值
      logic-not-delete-value: 0
      #逻辑已删除值
      logic-delete-value: 1
      id-type: id_worker_str
    configuration:
      log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl

ocloud:
  file:
    # 项目附件压缩包路径地址：
    preject-zip-path: C:\Users\14530\Desktop\project\
    upload-path: C:\Users\14530\Desktop\upload\


